#pragma once
typedef enum
{
	SGL_CAMERA_ORTHO = 0,
	SGL_CAMERA_GUI = 1,
	SGL_CAMERA_CUSTOM0 = 2,
	SGL_CAMERA_CUSTOM1 = 3,
	SGL_CAMERA_CUSTOM2 = 4,
	SGL_CAMERA_CUSTOM3 = 5,
	SGL_CAMERA_CUSTOM4 = 6,
	SGL_CAMERA_CUSTOM5 = 7,
} SGL_CameraID;

